name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Build project (if applicable)
      run: npm run build --if-present

    - name: Run tests
      run: npm run test  # Ensure test is a valid script in package.json

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        key: ${{ secrets.GIT_PRACTICE_VM_SSH }}
        host: ${{ secrets.GIT_PRACTICE_AWS_IP }}
        username: ${{ secrets.GIT_PRACTICE_AWS_UNAME }}
        script: |
          pm2 delete all
          cd /var/app/tdd-node.js
          git pull
          npm install
          pm2 start npm --name "app" -- start

