name : Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buils:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: action/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test test:staging
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        key: ${{secrets.GIT_PRACTICE_VM_SSH}}
        host: ${{secrets.GIT_PRACTICE_AWS_IP}}
        username: ${{secrets.GIT_PRACTICE_AWS_UNAME}}
        script: |
          pm2 delete all
          cd /var/app/tdd-node.js
          git pull
          npm install
          pm start npm -- start

        
